### ISSUE TITLE
Planering får fel sluttid

### ISSUE THREAD

**Issue by brstp** [24-timmarsseglingarna/app#5]
Starttid 12.08 gav planerad sluttid efter klockan 13. Skärmdump finns. Repeterbart.

**Comment by mbj4668** [comment]
Skicka gärna skärmdump!

**Comment by brstp** [comment]
Har skärmdump från 2019H. Kan inte ladda upp från mobilen.

Har seglat 75% av perioden. Planerar en rutt som bör vara rimlig om målfart = medelfart.  Äpplen visar rätt målfart men uppskattade rundningstider blir avsevärt senare än de borde, efter seglingsperiodens slut.

**Comment by mbj4668** [comment]
Jag noterade samma sak själv igår.  Mycket irriterande.

**Comment by mbj4668** [comment]
Fixed in 2.3.0
